= XTable Library for Arduino =

Support short set of informations, typically for configuration purpose, through generic structured items between EEPROM and SRAM. 

For more information about this library please visit us at
http://www.embeddedrevolution.info

== License ==

XTable is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
                                                              
XTable is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
                                                                       
You should have received a copy of the GNU General Public License 
along with XTable. If not, see <http://www.gnu.org/licenses/>. 
